# ----------------------- #
#      Main Configs       #
# ----------------------- #

# url:
# baseurl:
title: "Octal"
mail: cristian.hernandez@commonactionforum.net
author: cris hern√°ndez
description: "Can you see the stars?"
copyright: 'Copyright &copy; 2017 Octal. Some Rights Reserved.'
credits: 'Creditos: Landing Page created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/octalproject
